parameters:
#    b_sky_simple_page.example.class: BSky\Bundle\SimplePageBundle\Example

services:
#    b_sky_simple_page.example:
#        class: %b_sky_simple_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
