<?php

namespace BSky\Bundle\SimplePageBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findAllQuery(){
        $qb = $this->createQueryBuilder('p');
        
        $qb->select('p');
        
        return $qb->getQuery();
    }
}