<?php

namespace Rccc\Bundle\SimplePageBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findAllQuery(){
        $qb = $this->createQueryBuilder('p');
        
        $qb->select('p');
        
        return $qb->getQuery();
    }
    
    public function findBySlugAndSimilary($slug) {
        $qb = $this->createQueryBuilder('p');
        
        $qb->select('p.id, p.slug')
            ->where('p.slug LIKE :slug')
            ->setParameter('slug', $slug . '%');
        
        $pages = $qb->getQuery()->getArrayResult();
        $result = array();
        foreach ($pages as $page) {
            $result[$page['id']] = $page['slug'];
        }
        
        return $result;
    }
    
    public function deleteGroup($ids) {
        $qb = $this->createQueryBuilder('c');
        
        $qb->delete('BSkySimplePageBundle:Page', 'c')
         ->where($qb->expr()->in('c.id', $ids))
         ->getQuery()
         ->execute();
         
        $this->_em->flush();
    }
    
    public function publishGroup($ids) {
        $qb = $this->createQueryBuilder('c');
        
        $qb->update('BSkySimplePageBundle:Page', 'c')
         ->set('c.published_at', $qb->expr()->literal(date('Y-m-d H:i:s')))
         ->where($qb->expr()->in('c.id', $ids))
         ->getQuery()
         ->execute();
         
        $this->_em->flush();
    }
    
    public function unpublishGroup($ids) {
        $qb = $this->createQueryBuilder('c');
        
        $late = new \DateTime('2016-01-01 00:00');
        
        $qb->update('BSkySimplePageBundle:Page', 'c')
         ->set('c.published_at', $qb->expr()->literal($late->format('Y-m-d H:i:s')))
         ->where($qb->expr()->in('c.id', $ids))
         ->getQuery()
         ->execute();
         
        $this->_em->flush();
    }
}