bvm_simplepage_page_index:
     pattern:  /
     defaults: { _controller:BVMSimplePageBundle:Page:index }
     
bvm_simplepage_page_new:
     pattern:  /new
     defaults: { _controller:BVMySimplePageBundle:Page:new }
     
bvm_simplepage_page_edit:
     pattern:  /{id}/edit
     defaults: { _controller:BVMySimplePageBundle:Page:edit }
     requirements:
      id: \d+
      
bvm_simplepage_page_delete:
     pattern:  /{id}/delete
     defaults: { _controller:BVMySimplePageBundle:Page:delete }
     requirements:
      id: \d+
      
bvm_simplepage_page_groupprocess:
     pattern:  /groupprocess
     defaults: { _controller:BVMySimplePageBundle:Page:groupProcess }